// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpr-CY5lTripqFy9c3qSv0oTjQNK1oOQM',
    appId: '1:48446921533:web:8eee8343996b1a6c70c354',
    messagingSenderId: '48446921533',
    projectId: 'eos-clock-bbbf5',
    authDomain: 'eos-clock-bbbf5.firebaseapp.com',
    storageBucket: 'eos-clock-bbbf5.appspot.com',
    measurementId: 'G-B7CWX6VZ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANGRiFapXMz0mbnVKaWe9cG7y0Maem7BE',
    appId: '1:48446921533:android:6a9d050ef123a83370c354',
    messagingSenderId: '48446921533',
    projectId: 'eos-clock-bbbf5',
    storageBucket: 'eos-clock-bbbf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT7-jcX6aMfZmd_bhBiTc77JqzrQvzLbw',
    appId: '1:48446921533:ios:24eb5d9f87c243ee70c354',
    messagingSenderId: '48446921533',
    projectId: 'eos-clock-bbbf5',
    storageBucket: 'eos-clock-bbbf5.appspot.com',
    iosClientId: '48446921533-5tnf1i5l9n8fqi4q5b3o649n53iu8rs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosClock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT7-jcX6aMfZmd_bhBiTc77JqzrQvzLbw',
    appId: '1:48446921533:ios:24eb5d9f87c243ee70c354',
    messagingSenderId: '48446921533',
    projectId: 'eos-clock-bbbf5',
    storageBucket: 'eos-clock-bbbf5.appspot.com',
    iosClientId: '48446921533-5tnf1i5l9n8fqi4q5b3o649n53iu8rs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eosClock',
  );
}
